definitions:
  User:
    description: User represents the user for this application
    properties:
      email:
        description: The email address for this user
        type: string
        x-go-name: Email
      firstname:
        description: The name for this user
        type: string
        x-go-name: Firstname
      id:
        description: The ID for this user
        format: int64
        type: integer
        x-go-name: ID
      lastname:
        description: The lastname for this user
        type: string
        x-go-name: Lastname
    required:
    - id
    - firstname
    - lastname
    - email
    type: object
    x-go-package: github.com/GaijinZ/user-api/src/rest_api/model
info: {}
paths: {}
swagger: "2.0"
